name: SLSA Go releaser
on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

jobs:
  args:
    runs-on: ubuntu-latest
    outputs:
      commit-date: ${{ steps.ldflags.outputs.commit-date }}
      commit: ${{ steps.ldflags.outputs.commit }}
      version: ${{ steps.ldflags.outputs.version }}
      tree-state: ${{ steps.ldflags.outputs.tree-state }}
    steps:
      - id: checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - id: ldflags
        run: |
          echo "::debug::Generating build arguments..."
          COMMIT_DATE=$(git log --date=iso8601-strict -1 --pretty=%ct)
          COMMIT=$GITHUB_SHA
          VERSION=$(git describe --tags --always --dirty | cut -c2-)
          TREE_STATE=$(if git diff --quiet; then echo "clean"; else echo "dirty"; fi)
          
          echo "commit-date=$COMMIT_DATE" >> "$GITHUB_OUTPUT"
          echo "commit=$COMMIT" >> "$GITHUB_OUTPUT"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "tree-state=$TREE_STATE" >> "$GITHUB_OUTPUT"
          
          echo "::debug::Values generated:"
          echo "::debug::commit-date: $COMMIT_DATE"
          echo "::debug::commit: $COMMIT"
          echo "::debug::version: $VERSION"
          echo "::debug::tree-state: $TREE_STATE"

  build:
    needs: args
    permissions:
      id-token: write
      contents: write
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
    with:
      go-version: 1.23.2
      compile-builder: true
      evaluated-envs: |
        {
          "VERSION": "${{ needs.args.outputs.version }}",
          "COMMIT": "${{ needs.args.outputs.commit }}",
          "COMMIT_DATE": "${{ needs.args.outputs.commit-date }}",
          "TREE_STATE": "${{ needs.args.outputs.tree-state }}"
        }
